# Generated by Django 5.2.3 on 2025-06-14 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('company_url', models.URLField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Leave blank if this is your current position.', null=True)),
                ('description', models.TextField(help_text='Enter key responsibilities or achievements, separated by newlines.')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Experiences with lower numbers will appear first.')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('python', 'Python & Core Tools'), ('big_data', 'Big Data Technologies'), ('database', 'Databases & Warehousing'), ('cloud', 'Cloud Platforms'), ('devops', 'DevOps & CI/CD'), ('analytics', 'Analytics & Transformation')], max_length=50)),
                ('description', models.TextField()),
                ('icon_class', models.CharField(choices=[('fa-brands fa-python', 'Python Icon'), ('fa-solid fa-server', 'Server Icon'), ('fa-solid fa-database', 'Database Icon'), ('fa-solid fa-cloud', 'Cloud Icon'), ('fa-solid fa-code-branch', 'Code Branch Icon'), ('fa-solid fa-chart-line', 'Chart Line Icon')], default='fa-solid fa-server', max_length=50)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('github_url', models.URLField(blank=True, null=True)),
                ('live_url', models.URLField(blank=True, null=True)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Projects with lower numbers will appear first.')),
                ('tags', models.ManyToManyField(blank=True, to='portfolio_app.tag')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
    ]
