# Generated by Django 5.2.3 on 2025-06-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='category',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='description',
        ),
        migrations.AlterField(
            model_name='skill',
            name='icon_class',
            field=models.CharField(help_text="e.g., 'fab fa-python'", max_length=50),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
