# Generated by Django 5.2.3 on 2025-06-14 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_remove_skill_category_remove_skill_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='experience',
            name='summary',
            field=models.CharField(default='hellop', help_text='A brief one-line summary of the role.', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(help_text='Enter key achievements, separated by newlines.'),
        ),
    ]
