# Generated by Django 5.2.3 on 2025-06-14 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0003_experience_location_experience_summary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo_url', models.URLField(blank=True, help_text='A URL to your profile picture (e.g., from a CDN or another site).')),
                ('about_me_p1', models.TextField(blank=True, help_text="First paragraph of your 'About Me' section.")),
                ('about_me_p2', models.TextField(blank=True, help_text="Second paragraph of your 'About Me' section.")),
                ('github_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('resume_url', models.URLField(blank=True, help_text='A link to your resume PDF.')),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Profile',
            },
        ),
    ]
