# Generated by Django 5.2.3 on 2025-06-15 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0006_additionaltech_project_additional_tech'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='additional_tech',
        ),
    ]
