# Generated by Django 5.2.3 on 2025-06-16 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0007_remove_project_additional_tech'),
    ]

    operations = [
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('icon_class', models.CharField(help_text="e.g., 'fas fa-award'", max_length=50)),
                ('icon_bg_color', models.CharField(default='from-blue-500 to-cyan-500', help_text="e.g., 'from-blue-500 to-cyan-500'", max_length=50)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='portfolio_app.profile')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
    ]
